README.md, themes/Catppuccin-color-theme.json
Updated constants, function calls (with a ninja edit to not screw up args), keywords, and def keyword
=> fix: python

src/main.ts
=> fix: compile step

src/theme/extensions/error-lense.ts, src/theme/extensions/index.ts, src/theme/uiColors.ts
=> feat(extension): add support for Error Lens extension

src/theme/uiColors.ts
=> fix: added shadow to sticky scroll

README.md, package.json, src/theme/index.ts, src/theme/uiColors.ts, src/types/index.d.ts, src/utils.ts
Closes #73 by offering dimmed colors as an option.
=> feat: options for paired brackets

.github/workflows/publish.yml
=> ci: build orphan branch with compiled files

src/theme/uiColors.ts
In line with upcoming changes to JetBrains
=> feat: style breakpoint highlights

src/theme/uiColors.ts
=> fix(ui): inactive selection bg

src/theme/uiColors.ts
=> fix(ui): marketplace pre-release button & separator

src/theme/uiColors.ts
=> feat(options): support hex codes in `catppuccin.customUIColors`

src/theme/uiColors.ts
=> feat(ui): use accent color for more focused elements

src/theme/uiColors.ts
=> fix(ui): reduce current search highlight opacity

src/theme/tokens/index.ts, src/theme/tokens/php.ts
=> fix(syntax): PHP `this`, functions & builtin keywords

src/theme/semanticTokens.ts
=> feat(syntax): add Typst semantic tokens

src/theme/tokens/julia.ts
=> fix(syntax): Julia column symbols

src/theme/uiColors.ts
color0 and color15 were flipped, this is fixed now.
=> fix: terminal colors

src/theme/tokenColors.ts
=> fix: italic comments toggle

src/theme/tokens/javascript.ts
=> fix(syntax): Vue components color

src/theme/uiColors.ts
Adds Catppuccin colors to terminalCommandDecoration
=> feat(ui): add colors to command decorations

src/theme/tokens/php.ts
=> fix(syntax): PHP builtin function color, sky

README.md, src/hooks/updateVSCtypes.ts, src/theme/extensions/gitlens.ts, src/theme/extensions/index.ts, src/types/gitlens.d.ts, src/types/index.d.ts
Closes #176.
| Before | After |
|--------|--------|
| ![Screenshot_20231021_115725](https://github.com/catppuccin/vscode/assets/11707826/e4aa08b1-bd9e-4466-8402-9d702efcb406) | ![Screenshot_20231021_115906](https://github.com/catppuccin/vscode/assets/11707826/6ce76009-cb66-405e-a28b-b0b9bcf7fb8c) |
=> feat(extension): add GitLens integration

src/theme/tokens/javascript.ts
=> fix(syntax): JSDoc variables

.github/workflows/chromatic.yml, .github/workflows/ci.yml, .github/workflows/release-please.yml, package.json
Also makes the Chromatic token public so that visual checks run on forked repositories & PRs.
=> ci: prepare yarn v4

.github/workflows/chromatic.yml, src/theme/tokens/cpp.ts, src/theme/tokens/index.ts
=> fix(syntax): improve cpp textmate tokens

README.md
=> small syntax fix in nixos example -  README fix

README.md, src/hooks/updateVSCtypes.ts, src/theme/extensions/github-pull-request.ts, src/theme/extensions/index.ts, src/types/github-pull-request.d.ts, src/types/index.d.ts
Adds support for [GitHub Pull Request and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)
=> feat(extension): GitHub Pull Request and Issues

src/theme/uiColors.ts
Closes #229 & a minor redesign of how the tab bar looks, so it looks more like the default theme.
=> feat(ui): redesign tab bar

src/theme/tokens/html.ts, src/theme/tokens/javascript.ts
=> feat(markup): use pink for Components

src/theme/uiColors.ts, src/theme/utils.ts
=> feat(ui): redesign search match colors

packages/catppuccin-vsc/src/theme/tokens/javascript.ts
=> fix(js/ts): JSDoc params color, typeof as keyword

packages/catppuccin-vsc/src/theme/uiColors.ts
=> fix(ui): command center appearance, de-emphasize borders

nix/default.nix
=> build(nix): fix build

packages/catppuccin-vsc/src/theme/uiColors.ts
=> fix(ui): unverified breakpoints

packages/catppuccin-vsc/src/theme/uiColors.ts
=> fix(ui): selection color for non-editor context

packages/catppuccin-vsc/package.json, packages/catppuccin-vsc/src/hooks/updatePackageJson.ts, packages/catppuccin-vsc/src/main.ts, packages/catppuccin-vsc/src/theme/index.ts, packages/catppuccin-vsc/src/types/index.d.ts, packages/catppuccin-vsc/src/utils.ts
=> feat(options): add option to disable icon pack sync

.github/workflows/release-please.yml
=> ci: fix marking theme release as latest

README.md
=> docs: remove shikiji

.github/workflows/release-please.yml
=> ci: add token for marking latest release step

packages/catppuccin-vsc/package.json, packages/catppuccin-vsc/src/hooks/updatePackageJson.ts
=> fix: switch to `esm.sh` for schemas

nix/yarn-project.nix, packages/catppuccin-vsc-storybook/package.json, packages/catppuccin-vsc/package.json, packages/catppuccin-vsc/src/theme/index.ts, packages/catppuccin-vsc/src/theme/uiColors.ts, packages/catppuccin-vsc/src/types/index.d.ts, packages/catppuccin-vscode/package.json, yarn.lock
Went for the implementation that results in the fewest number of lines changed.
Will most likely push out a breaking change on the TS library so that we have a
nicer API to work with here.
Closes #445
=> feat: apply new ANSI terminal colours

packages/catppuccin-vsc/package.json
Hoping to revamp the way this works in a future PR.
=> chore: sync `$ref` tag

packages/catppuccin-vsc/package.json, packages/catppuccin-vsc/schemas/customUIColors.schema.json, packages/catppuccin-vsc/src/hooks/constants.ts, packages/catppuccin-vsc/src/hooks/updateSchemas.ts
Updates workbench colors using data from [ota-meshi/extract-vscode-schemas](https://github.com/ota-meshi/extract-vscode-schemas).
=> fix: update JSON schema for `customUIColors`
