README.md

I saw the readme was still missing a specified Usage section, so I added that 😄 
These will probably get outdated once the theme is uploaded to the marketplace but for now it could possible help some people out. Like in #5

Fix: Add install tutorial in readme

---

themes/Catppuccin-color-theme.json

- Change brackets to maroon
- Change 'using' directive (namespaces) to teal (same as include)
- Change compound assignment and ternary operators to sky to match other logical/assignment operators
- Change variables to not italic since 99% of my files were italic otherwise
- Removed some redundant syntax definitions

fix: cpp operators

---

themes/Catppuccin-color-theme.json

As pointed out in catppuccin/sublime-text#1, the active line number color in neovim is green. I changed it here accordingly. Not sure if a different color is preferred by others, but imo the difference between gray1 and gray2 wasn't nearly enough.

fix: active line number

---

themes/Catppuccin-frappe-color-theme.json
themes/Catppuccin-latte-color-theme.json
themes/Catppuccin-macchiato-color-theme.json
themes/Catppuccin-mocha-color-theme.json

C++ variables were all `Flamingo` which made it hard to differentiate between properties/parameters and local variables, and made files very orange, so I changed them to `Text`.

fix: c++ variables

---

README.md

Some users may not want italics within their code, this configuration ensures that no italics are shown in the code.

docs(README): Add config on how to disable italics

---

README.md

Not all italics were removed with the current config in the README. It seems VSCode doesn't recognize nested string textmate scopes in the settings.json file the same way it does in the source theme file, so it was ignoring several items. This fix separates all scopes to ensure all italics are removed.

docs: fix disable-italic config

---

src/theme/index.ts
themes/Catppuccin-frappe-color-theme.json
themes/Catppuccin-latte-color-theme.json
themes/Catppuccin-macchiato-color-theme.json
themes/Catppuccin-mocha-color-theme.json

Making whitespaces more distinguishable. Closing #47 issue.
**Before / After:**
Mocha
Macchiato
Frappe
Latte

feat: improved whitespaces highlighting

---

src/theme/uiColors.ts
themes/frappe.json
themes/latte.json
themes/macchiato.json
themes/mocha.json

Having both editor.wordHighlightStrongBackground and editor.selectionBackground set to the same value makes it impossible to see selections in the active token. Applying 50% opacity to the token highlight restores functionality; I haven't checked to see if this issue exists in the other palettes.

Change editor.wordHighlightStrongBackground

---

.vscodeignore
src/main.ts
src/theme/index.ts
src/utils.ts

Fixes an issue I overlooked in #38. When updating from the marketplace, you had to change a setting, to trigger a recompile.
Now the theme auto-detects **first installations for each version**, and only recompiles if required.
I also improved the prompt so that the user knows why a reload is required: 
After pressing reload in the 2nd screenshot, the theme restores itself to my tweaks in the first screenshot:
`#000000` as `base`, `mantle`, `crust` and `#ff69b4` as `pink`.

fix: trigger re-compile after updating the extension

---

README.md
package.json
src/theme/index.ts
src/theme/uiColors.ts
src/types/index.d.ts
src/utils.ts

@watatomo brought this up in Discord:
This adds `catppuccin.customUIColors` in the JSON preferences:
You can either use `rosewater` to use the current Palettes `rosewater` color, or `rosewater 0.2` for `rosewater` with 20% opacity.
Please download [this artifact](https://github.com/catppuccin/vscode/suites/9041405713/artifacts/417696993) from [the CI](https://github.com/catppuccin/vscode/actions/runs/3359163539) and give it a go.

feat(ui): named color customizations

---

src/theme/uiColors.ts

Fixes an issue where the opacity value would cause a crash when trying to set opacity for "accent".
Closes #69

fix(named colors): accent opacity

---

package.json
src/theme/index.ts
src/theme/tokenColors.ts
src/theme/uiColors.ts
src/types/index.d.ts
src/utils.ts

i had a go at this to see what it would look like.
<details>
<summary>latte</summary>
</details>
<details>
<summary>frappé</summary>
</details>
<details>
<summary>macchiato</summary>
</details>
<details>
<summary>mocha</summary>
</details>
let me know your thoughts!
closes #92

add an option for a subtle border on some UI elements

---

src/theme/uiColors.ts

Closes #104 
Currently the highlight border is the same as editor background (`palette.base`) which overrides the highlight background, makes it looks like the highlight doesn't cover the first character. This PR changes the border to transparent, keep the minimal look of the theme while fixing above problem.
*Before fix*
*After fix*

fix: highlight border to be transparent

---

src/theme/tokenColors.ts

Should be self explanatory. Dollar symbol is not assigned a color as it is right now. Pretty simple fix, I'm not sure if the `all variable` object is the correct place to put it, but as we're talking about variable definitions I think it makes sense semantically.

fix(ui): Give PHP variable definitions correct color

---

src/main.ts
src/theme/uiColors.ts
tsconfig.json

Closes #159.
Pretty stupid error that got overlooked because I forgot that I hadn't set tsconfig to strict yet.

fix(compiler): compile when icons aren't installed

---

src/theme/tokens/diff.ts
src/theme/tokens/index.ts

This PR adds syntax highlighting support for `.diff` files.
| Before | After |
|--------|--------|
| ![diff syntax highlighting before](https://github.com/catppuccin/vscode/assets/43011723/9bdacc64-f817-47b0-b291-847c92035dff) | ![diff syntax highlighting after](https://github.com/catppuccin/vscode/assets/43011723/0082651b-0358-444d-bbb7-7fa3358b56a2)|

feat(syntax): Diff highlighting

---

src/theme/tokens/cs.ts
src/theme/tokens/index.ts

| Before | After |
|--------|--------|
| ![before](https://github.com/catppuccin/vscode/assets/43011723/23e4cade-2dcd-463a-8034-ffb82fc492a6) | ![after](https://github.com/catppuccin/vscode/assets/43011723/3dd6f4a8-7af1-4fa5-b9f2-10e97dbc1962) | 
- Closes #178

fix(syntax): C# interpolated strings highlighting

---

src/theme/uiColors.ts

fix: use `focusBorder` variable for keyboard navigation highlights

---

src/theme/tokens/nix.ts

on a second thought, paths should probably stand out more
BEGIN_COMMIT_OVERRIDE
END_COMMIT_OVERRIDE

fix(syntax): nix path colors

---

src/theme/tokens/css.ts

This is literally just a fix to force a new release since GitHub actions crashed, when the last release was supposed to run.

fix(syntax): CSS operators, preprocessor parent selectors

---

nix/default.nix
nix/shell.nix

Turns out `vsce` was the slow step, not the build.

build(nix): optimize build speed

---

README.md
nix/default.nix
src/hooks/generateThemes.ts

I mistakenly called the option `accentColor` when `accent` was needed; added a deprecation note.

fix(nix): accent color wasn't applying correctly

---

packages/catppuccin-vsc/src/theme/tokens/index.ts
packages/catppuccin-vsc/src/theme/tokens/regex.ts

feat(regex): add dedicated syntax highlighting for regex

---

packages/catppuccin-vsc/build.ts

It turns out that splitting caused some odd glitches when upgrading, like VSCode still referring to a differently named chunk, and thus being unable to load the extension.
This almost 2x's the build size, but I don't really have other ideas.

build: turn off code splitting

---

packages/catppuccin-vsc/package.json
packages/catppuccin-vsc/src/hooks/updatePackageJson.ts

catppuccin-vsc v3.10.0 will be tagged as `catppuccin-vsc-v3.10.0` instead of `v3.10.0`, so this changes the tag accordingly.

build: rename tag in schema URLs

---

packages/catppuccin-vsc/src/theme/uiColors.ts

This PR fixes unthemed activity bar when its placed at the top.
Before :
After :

feat(ui): add colors to activity bar when placed on top

---

packages/catppuccin-vscode/src/index.ts

Without this fix, Shiki (at least in Astro) would generate wrong class names:
This could be fixed via
```ts
import { mocha } from "@catppuccin/vscode";
import { defineConfig } from "astro/config";
export default defineConfig({
markdown: {
shikiConfig: {
theme: {
...mocha,
name: "catppuccin-mocha",
},
},
},
});
```
but it makes sense to shim this for the library user.

fix: shim theme name for shiki

---

packages/catppuccin-vsc/src/theme/uiColors.ts

attempt nr 2 for #331 
latte might need a bump in opacity

feat: rework selection background

---

.github/workflows/release-please.yml

The syntax for this logic is so atrocious I really can't be bothered testing lmfao
Guess we'll find out on the next episode that is the shitshow of GitHub Actions

ci: mark theme release as latest

---

flake.lock
nix/default.nix

Fixes the build for nixpkgs with https://github.com/NixOS/nixpkgs/pull/289721.
Closes #367.

build(nix): fix for new sourceRoot attribute

---

packages/catppuccin-vsc/src/main.ts
packages/catppuccin-vsc/src/utils.ts

users can set their active color theme either with `workbench.colorTheme` or with `window.autoDetectColorScheme`.
in the latter case, four other settings control the theme that is enabled.
this commit updates the `syncToIconPack` function to take `autoDetectColorScheme` into account and correctly sync the icon theme when it's enabled.
fixes #398 (or rather a secondary issue that was raised there)

feat: support `autoDetectColorScheme` in icon sync

---

packages/catppuccin-vsc/src/main.ts

The root cause of the problem is that VS Code seems to fire the `onDidChangeActiveColorTheme` event **before** the config is persisted, thus our `syncToIconPack()` runs too early and in turn `getActiveTheme()` reads back the not-yet-updated theme from the configuration.
The fix is to listen for both the config change _and_ the active theme change (needed to handle the `autoDetectColorScheme` edge case).
Solves #430.

Fix desync between icon pack and color theme

---

packages/catppuccin-vsc/src/theme/uiColors.ts

fix: set `editor.wordHighlightStrongBackground`

---

nix/default.nix

The `icon.png` was missing from the nix built extension.

fix: include profile picture when built with nix

---

packages/catppuccin-vsc/src/theme/tokens/index.ts

Updates comments and operators to match https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#code-editors.

fix(tokens): change comments from `overlay0` to `overlay2`

---

flake.lock
nix/default.nix

Breaks on current nixos-unstable channel.
- https://github.com/NixOS/nixpkgs/pull/354740
- `vscode-utils.buildVscodeExtension` now requires pname as an argument

fix(nix): buildVscodeExtension requires pname

---

packages/catppuccin-vsc/src/theme/tokens/markdown.ts

As mentioned in Discord, these new colors are what the style guide specifies:

fix(tokens/markdown): match headings 5 & 6 to style guide

---

packages/catppuccin-vsc/src/theme/tokens/python.ts

Makes Python more in line with how we highlight every other language.

fix(tokens/python): mauve builtin types, peach language constants

---

.github/workflows/ci.yml
.github/workflows/release-please.yml
packages/catppuccin-vsc/build.ts
packages/catppuccin-vsc/package.json
packages/catppuccin-vsc/src/hooks/updatePackageJson.ts

As announced in the ["What's happening to Azure Data Studio? - Microsoft"](https://learn.microsoft.com/en-gb/azure-data-studio/whats-happening-azure-data-studio) article, Azure Data Studio has been retired and will no longer be supported past February 28th 2026.
This PR removes support for building on Azure Data Studio, simplifying our build process even more and making local development easier as we no longer have to "rehydrate" the `package.json` twice on each build.

refactor: stop building for Azure Data Studio

---

.vscode/launch.json
README.md
packages/catppuccin-vsc/build.ts
packages/catppuccin-vsc/package.json
packages/catppuccin-vsc/src/hooks/packageJson.ts
packages/catppuccin-vsc/src/hooks/updateSchemas.ts

This PR _finally_ fixes our debugging configuration and improves upon the old method.
Now, you can run the "Debug & Watch Files" configuration to spawn a new instance of VSCode and see immediate feedback from changing the Typescript source code.
I've also changed the logic to not regenerate the `package.json` in development mode since that was being a pain during debugging. 
@backwardspy let me know if the new config works for you too.

refactor: fix extension debugging

---

packages/catppuccin-vsc/src/theme/tokens/index.ts
packages/catppuccin-vsc/src/theme/tokens/typst.ts

Closes #505 
Tested with a sample file:

fix(tokens): consistently style typst headings

---

packages/catppuccin-vsc/package.json
packages/catppuccin-vsc/src/hooks/packageJson.ts

Relates to https://github.com/catppuccin/vscode/issues/452
The theme customisation is implemented in such a way where the only valid scope is `application`. This will reduce user confusion if they try to configure this in their profile or workspace.
E.g.

fix: specify `scope: application` for all settings

---

packages/catppuccin-vsc/src/theme/uiColors.ts

This project already has support for the super fancy graph from the excellent GitLens extension.
But what about us normies who also use the built-in SCM Graph?
This PR adds support for the poor-man's GitLens graph.
| Before | After |
|--------|--------|
|<img width="630" height="647" alt="Screenshot 2025-08-05 at 13 49 51" src="https://github.com/user-attachments/assets/fccd459a-be05-4116-b530-45c569dc2fb6" />|<img width="631" height="645" alt="Screenshot 2025-08-05 at 13 59 55" src="https://github.com/user-attachments/assets/3ded8a62-d578-4648-91f6-06f246d0851d" />|

feat: support built-in git scm graph

---

packages/catppuccin-vsc/src/utilities.ts

Exposing the LOG as a constant variable _should_ be fine? It doesn't give me
any typed information on if it can throw an error or return as undefined so I
think it's okay?
It now comes under the outputs:
The files in hooks/** should stay as console.log since it's not running under VSCode. I might actually try to create a custom rule in eslint for this.
Supersedes #555

fix: use `LogOutputChannel` instead of `console.log`
